version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "anoop-kunjuraman-com-site"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1iz25k2wydy48"
s3_prefix = "anoop-kunjuraman-com-site"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "HTMLBucketName=\"anoop.kunjuraman.com\" CustomDomainName=\"anoop.kunjuraman.com\" AcmCertificateArn=\"arn:aws:acm:us-east-1:414954339574:certificate/355fc4e1-57ca-46d8-babc-86fe1d771b47\" ComputeType=\"BUILD_GENERAL1_SMALL\" EnvironmentType=\"LINUX_CONTAINER\" GitHubOwner=\"anoopengineer\" GitHubRepo=\"anoop-kunjuraman-site\""

